include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_types_on_closure_parameters: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_typing_uninitialized_variables: true 
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    super_goes_last: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_library_directive: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    always_declare_return_types: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_to_and_as_if_applicable: true
    no_leading_underscores_for_local_identifiers: true
    no_leading_underscores_for_library_prefixes: true